default:
  image: alpine:3.19

stages:
  - lint

lint:bash:
  stage: lint
  image: koalaman/shellcheck-alpine:v0.9.0
  script:
    - echo "Iniciando análisis estático de scripts Bash..."
    - shellcheck scripts/*.sh

lint:dockerfile:
  stage: lint
  image: hadolint/hadolint:latest-alpine
  script:
    - echo "Iniciando análisis de seguridad del Dockerfile..."
    - hadolint --ignore DL3008 --ignore DL3025 app/Dockerfile

lint:python:
  stage: lint
  image: python:3.11-slim
  before_script:
    - pip install --no-cache-dir flake8
  script:
    - echo "Iniciando análisis estático del código Python..."
    - flake8 app/main.py --max-line-length=120 --ignore=E501,W503,W292
