replicaCount: 2

image:
  repository: registry.gitlab.com/cnp-group1/devops-portfolio-project
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  environment: "production"
  port: "8080"
  logLevel: "INFO"

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

probes:
  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10