name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Code & IaC Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Lint Python Code (Flake8)
        run: |
          pip install flake8
          flake8 app/main.py --max-line-length=120 --ignore=E501,W503,W292

      - name: Lint Shell Scripts (ShellCheck)
        uses: ludeeus/action-shellcheck@master
        with:
          scans: scripts

      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: app/Dockerfile
          ignore: DL3008,DL3025

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Validate Terraform Format & Syntax
        run: |
          cd terraform
          terraform fmt -check
          terraform init -backend=false
          terraform validate

  build:
    name: Docker Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devops-portfolio-api:${{ github.sha }} ./app

  security:
    name: Vulnerability & IaC Security Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Local Image for Scanning
        run: docker build -t devops-portfolio-api:${{ github.sha }} ./app

      - name: Run Trivy Vulnerability Scanner (Container)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devops-portfolio-api:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      - name: Run Trivy IaC Scanner (Terraform)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'terraform/'
          format: 'table'
          exit-code: '0'